---
site:
  title: "Network automation: Backup and restore"
  url: https://redhat-scholars.github.io/course-template
  start_page: modules::index.adoc

asciidoc:
  attributes:
    lab_name: "Network automation: Backup and restore"
    release-version: master
    page-pagination: true


content:
  sources:
    - url: ./
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.3/ui-bundle.zip
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
